const withMT = require("@material-tailwind/react/utils/withMT");
const { colors } = require("@mui/material");

module.exports = withMT({
  content: ["./src/**/*.{html,js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        default: "var(--default)",
        accent: "var(--accent)",
        borderColor: "var(--border)",
        borderTopColor: "var(--border-top)",
        borderBottomColor: "var(--border-bottom)",
        inputError: "var(--input-error)",
        secondaryButton: "var(--secondary-button)",
        selectedOptionBg: "var(--selected-option-bg)",
        sidebar: "var(--sidebar)",
        sidebarMenu: "var(--sidebar-menu)",
        sidebarMenuBg: "var(--sidebar-menu-bg)",
        accentInvert: "var(--accent-invert)",
        modalBg: "var(--modal-bg)",
        warning: "var(--warning)",
        tabBg: "var(--tab-bg)",
        listItemBorder: "var(--list-item-border)",
        listItemHoverBorder: "var(--list-item-hover-border)",
        listItemHoverBg: "var(--list-item-hover-bg)",
        linkText: "var(--link-text)",
        hoverText: "var(--hover-text)",
        yellow: "var(--yellow)",
        amber: "var(--amber)",
        helperText: "var(--helper-text)",
        tooltipText: "var(--tooltip-text)",
        tooltipBg: "var(--tooltip-bg)",
        disableAccent: "var(--disable-accent)",
        disableInputBg: "var(--disable-input-bg)",
        inputPlaceholder: "var(--input-placeholder)",
        disableInputPlaceholder: "var(--disable-input-placeholder)",
        scrollButtonBg: "var(--scroll-button-bg)",
      },
    },
  },
  plugins: [],
});
